tools:
    # external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
        
build:
    environment:
        php: 7.2
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run
                    - command: phpcs-run ./src/
                        
        coverage:
            tests:
                override:
                    - command: 'phpunit --coverage-clover=clover.xml'
                      coverage:
                        file: 'clover.xml'
                        format: 'clover'
                  
filter:
    excluded_paths:
        - './tests/*'
checks:
    php: true
coding_style:
    php:
        indentation:
            general:
                size: 2
        spaces:
            around_operators:
                additive: false
                multiplicative: false
            other:
                after_type_cast: false
