tools:
    external_code_coverage: true
build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
        tests: true
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        indentation:
            general:
                size: 2
        spaces:
            around_operators:
                additive: false
                multiplicative: false
            other:
                after_type_cast: false
